### ISSUE TITLE
Select database

### ISSUE THREAD

**Issue by Zyles** [DevAngsy/nestjs-redis#109]
## Feature Request

Any ETA on ability to select database? Was looking into this package but had to drop it because of that.

Thanks.

**Comment by bttger** [comment]
You can do this either in the [config](https://github.com/liaoliaots/nestjs-redis/blob/main/docs/v3/redis.md#usage) or with the [select](https://redis.io/commands/select) command.

**Comment by Zyles** [comment]
Great! Thanks.
