### ISSUE TITLE
Make global module as an option

### ISSUE THREAD

**Issue by lhr0909** [DevAngsy/nestjs-redis#175]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

I would like to set up the redis module in a non-global way, so is there a chance we can make it configurable? Thanks!

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@liaoliaots/nestjs-redis/dist/redis/redis.module.js b/node_modules/@liaoliaots/nestjs-redis/dist/redis/redis.module.js
index 8d6de0a..d72312e 100644
--- a/node_modules/@liaoliaots/nestjs-redis/dist/redis/redis.module.js
+++ b/node_modules/@liaoliaots/nestjs-redis/dist/redis/redis.module.js
@@ -29,7 +29,7 @@ let RedisModule = RedisModule_1 = class RedisModule {
             ...redisClientProviders
         ];
         return {
-            global: true,
+            global: false,
             module: RedisModule_1,
             providers,
             exports: [redis_manager_1.RedisManager, ...redisClientProviders]
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by lhr0909** [comment]
I can submit a PR if you want me to (not with the above patch but exposing `global` as an option).

**Comment by liaoliaots** [comment]
@lhr0909 thanks for opening the issue!
It's a good suggestion and I will look into it ASAP.

**Comment by liaoliaots** [comment]
please follow the steps below:

1. bump `@liaoliaots/nestjs-redis` to `6.0.0`

```sh
npm install --save @liaoliaots/nestjs-redis@6
```

2. create a shared module:

```TypeScript
// shared-redis.module.ts

import { Module } from '@nestjs/common';
import { RedisModule } from '@liaoliaots/nestjs-redis';

@Module({
    imports: [
        RedisModule.forRoot(
            {
                readyLog: true,
                config: {
                    host: '127.0.0.1',
                    port: 6380,
                    password: 'bitnami'
                }
            },
            false // <--- make the module non global
        )
    ],
    exports: [RedisModule] // <--- important: share this module
})
export class SharedRedis {}
```

3. import `SharedRedis` to your business module:

```TypeScript
// cats.module.ts

import { Module } from '@nestjs/common';
import { CatsService } from './cats.service';
import { CatsController } from './cats.controller';
import { SharedRedis } from '../shared-redis.module';

@Module({
    imports: [SharedRedis], // <---
    providers: [CatsService],
    controllers: [CatsController]
})
export class CatsModule {}
```

4. test

```sh
npm run start:dev
```

**Comment by lhr0909** [comment]
好的！这两天我会整合测试一下。感谢🙏

**Comment by AvantaR** [comment]
@liaoliaots 

Does it work for you? I've got error as below:
```
[Nest] 603402  - 03/01/2022, 2:44:19 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the HistoryRepository (?). Please make sure that the argument RedisModule:default at index [0] is available in the HistoryModule context.

Potential solutions:
- If RedisModule:default is a provider, is it part of the current HistoryModule?
- If RedisModule:default is exported from a separate @Module, is that module imported within HistoryModule?
  @Module({
    imports: [ /* the Module containing RedisModule:default */ ]
  })
```

Everything looks fine in the module's configuration.

**Comment by lhr0909** [comment]
@AvantaR I upgraded on my end and it worked as expected (I didn't do the shared module trick though). Curious why this happens. Maybe @liaoliaots can help 😄

**Comment by AvantaR** [comment]
Ok, it was not related to this module, but to the circular imports in my code. Thanks.

**Comment by liaoliaots** [comment]
@AvantaR It may be useful for you to import files in the correct order:

As mentioned above, decorator `@InjectRedis` is used in `CatsService`. If import `SharedRedis` before `CatsService`, nest will throw an error, as shown below. Because some methods in `RedisModule` will get called after the `@InjectRedis` calls and therefore `RedisModule` will create/re-export providers correctly.

![Screenshot_20220302_233757](https://user-images.githubusercontent.com/27341089/156395296-5b643414-500a-4a92-b7e3-3b50c7b89703.png)

If import `CatsService` first, it works as expected:

![Screenshot_20220302_233830](https://user-images.githubusercontent.com/27341089/156400839-6c6e54d9-130b-4020-b617-6792263817bb.png)


__- - OR - -__
You can use `RedisModule` in the global scope, that error will not exist.

**Comment by liaoliaots** [comment]
Please check out the new version: version 10 of [@liaoliaots/nestjs-redis](https://www.npmjs.com/package/@liaoliaots/nestjs-redis/v/10.0.0).
