### ISSUE TITLE
ClusterAllFailedError: Failed to refresh slots cache.

### ISSUE THREAD

**Issue by khangvu07031996** [DevAngsy/nestjs-redis#187]
Thank for your contribute, so i have a issue when implement.
when i use cluster module, if  one node  timeout connect, i can not get data from another nodes and get error.

**Comment by liaoliaots** [comment]
Your problem may be relevant to these cases:

1. your redis server cluster config, please read through the documentation(hash-slot and master-replica): https://redis.io/docs/manual/scaling/#redis-cluster-master-replica-model
2. your ioredis cluster config: https://github.com/luin/ioredis#cluster
