### ISSUE TITLE
Nestjs Microservice ioredis strategy connector

### ISSUE THREAD

**Issue by ali-master** [DevAngsy/nestjs-redis#203]
### Is your feature request related to a problem? Please describe it

Nestjs microservice just supports the node-redis and there is no strategy for the ioredis.

### What is the motivation / use case for changing the behavior?

Develop an ioredis' strategy connector for the Nestjs microservice.

**Comment by liaoliaots** [comment]
First, this is a **good idea**, I will look into it ASAP.
But I have a heavy workload, I will not implement it in a short time. I'm so sorry.

**Comment by ali-master** [comment]
Hi there

Hope you are doing well
May you implement this feature?
I appreciate it if you do it. 🌹

**Comment by ali-master** [comment]
Any update?

**Comment by liaoliaots** [comment]
I’m buried in work. I will not implement it in a short time, sorry for that. 🙂

**Comment by ali-master** [comment]
I implemented this feature manually and I'll create a pull request here to help other people to use this feature.

**Comment by liaoliaots** [comment]
@ali-master 
Nest microservices is migrating from node-redis to ioredis: [_**PR**_](https://github.com/nestjs/nest/pull/8798).
