### ISSUE TITLE
Nestjs V9 support

### ISSUE THREAD

**Issue by mdwekat** [DevAngsy/nestjs-redis#305]
## Expected Behavior

For the module to work with Nestjs V9

## Current Behavior

When installing the package it was unable to resolve the dependency tree
```shell
peer @nestjs/common@"^8.0.0 || ^7.0.0" from @liaoliaots/nestjs-redis@8.2.2
```

## Steps to Reproduce (for bugs)

1. Create new V9 Nestjs.
2. Try to install the module `npm i @liaoliaots/nestjs-redis`

## Context

Trying to use the package with Nestjs app V9

## Your Environment

-   Version used: v8.2.2
-   NestJS version: v9.0.3
-   Node.js version: v16.15.1
-   Operating System and version (macOS, Windows, Linux): macOS, Linux

**Comment by liaoliaots** [comment]
Version 9 will be released soon, for now, please use `@liaoliaots/nestjs-redis@9.0.0-next.1` instead. Sorry for waiting a long time.

**Comment by mdwekat** [comment]
Awesome waiting for that, Thanks!

**Comment by liaoliaots** [comment]
`@liaoliaots/nestjs-redis` v9 is now available.
https://github.com/liaoliaots/nestjs-redis/releases/tag/v9.0.0

**Comment by mdwekat** [comment]
Awesome, like a charm!
