### ISSUE TITLE
 Redis client "default" was not found in the application context.

### ISSUE THREAD

**Issue by AarNtyon** [DevAngsy/nestjs-redis#339]
Hello,liaoliao, I quoted your dependency in the project. 
I have encountered a problem and would like to ask you.

in app.module.ts
```
@Module({
  imports: [
    ConfigModule.load(resolve(__dirname, 'config', '**/!(*.d).{ts,js}')),
    RedisModule.forRootAsync({
      useFactory: (config: ConfigService) => config.get('dbConfig').redis,
      inject: [ConfigService],
    }),
  ],
})
````
in redis.service.ts
```
import { Injectable } from '@nestjs/common'
import {  RedisService } from '@liaoliaots/nestjs-redis'
import Redis from 'ioredis';

@Injectable()
export class redisServiceCustom {
  // Redis ===> Cannot use namespace 'Redis' as a type.
  private readonly redis: Redis;

  constructor(private readonly redisService: RedisService) {
    this.redis = this.redisService.getClient();
  }
}
```
at this time, the terminal throws an error
```Redis client "default" was not found in the application context.```

**Comment by AarNtyon** [comment]
close

**Comment by LbhFront-end** [comment]
How to solve?

**Comment by AarNtyon** [comment]
`  RedisModule.forRootAsync({
      useFactory: async (config: ConfigService): Promise<RedisModuleOptions> => ({
        config: config.get('dbConfig').redis
      })
    })
`
try this

**Comment by LbhFront-end** [comment]
> ` RedisModule.forRootAsync({ useFactory: async (config: ConfigService): Promise<RedisModuleOptions> => ({ config: config.get('dbConfig').redis }) })` try this

thanks! But the error is can't find specific name that i define

**Comment by AarNtyon** [comment]
import RedisModuleOptions from this  package
