### ISSUE TITLE
Update Nestjs dependencies

### ISSUE THREAD

**Issue by emanuelmcp** [DevAngsy/nestjs-redis#516]
Update nestjs dependencies to latest version

**Comment by pneme** [comment]
+1, allow @nestjs/* at version 10

**Comment by mahsumurebe** [comment]
Hi @liaoliaots.

I submitted a pull request (#517). Please check and update the npm package. 

Thank you all.

**Comment by chunkhang** [comment]
hey @mahsumurebe, i think the peer dependencies for the packages also need to be bumped individually

**Comment by mahsumurebe** [comment]
Hey @chunkhang 

What peer dependencies are you talking about? There are also changes to the pnpm-lock.yaml file. Which ones are missing?

**Comment by chunkhang** [comment]
@mahsumurebe i think these files:

- https://github.com/liaoliaots/nestjs-redis/blob/fc697638af9ecf80ad2992a923047c626f2bf95b/packages/redis-health/package.json#L49-L53
- https://github.com/liaoliaots/nestjs-redis/blob/fc697638af9ecf80ad2992a923047c626f2bf95b/packages/redis/package.json#L43-L47

**Comment by heiba** [comment]
Any updates please ?

**Comment by Distortedlogic** [comment]
bump for dep bump

**Comment by hotsezus** [comment]
[!518](https://github.com/liaoliaots/nestjs-redis/pull/518) is actually more acurate beacause it does not introsuce breaking change and is not changing something unnecessarily

**Comment by songkeys** [comment]
It looks like the author has not been keeping up with the repository for some time. I just forked it to [https://github.com/Songkeys/nestjs-redis](https://github.com/Songkeys/nestjs-redis) and updated the NestJS dependencies to `^10.0.0`.

The npm package is `@songkeys/nestjs-redis` and can be installed if you're blocked from migrating to NestJS 10 because of it. Once the author comes back, you can change it back to `@liaoliaots/nestjs-redis`.

**Comment by heiba** [comment]
Thanks @Songkeys. We're planning to use your package as it unblocks us and allows us to upgrade to Nest v10. Thanks a lot for your efforts.

**Comment by simplenotezy** [comment]
> It looks like the author has not been keeping up with the repository for some time. I just forked it to https://github.com/Songkeys/nestjs-redis and updated the NestJS dependencies to `^10.0.0`.
> 
> The npm package is `@songkeys/nestjs-redis` and can be installed if you're blocked from migrating to NestJS 10 because of it. Once the author comes back, you can change it back to `@liaoliaots/nestjs-redis`.

Got a package for [health](https://www.npmjs.com/package/@liaoliaots/nestjs-redis-health) as well, by chance?

**Comment by songkeys** [comment]
> Got a package for [health](https://www.npmjs.com/package/@liaoliaots/nestjs-redis-health) as well, by chance?

@simplenotezy Yes. Try https://www.npmjs.com/package/@songkeys/nestjs-redis-health.

**Comment by fingeromer** [comment]
any updates?

**Comment by ZhaoKunLong** [comment]
any updates?

**Comment by andredelima92** [comment]
Any news?

**Comment by jacobsandersen** [comment]
Hoping this will be updated. For now, using @Songkeys fork - hopefully that one stays updated.. :)

**Comment by evyros** [comment]
Moved to using @Songkeys - thanks

**Comment by awuzi** [comment]
Any news?

**Comment by mentos1386** [comment]
Another solution for this is to use `overrides` in your `package.json`. Like this:
```json
  "overrides": {
    "@liaoliaots/nestjs-redis": {
      "@nestjs/common": "^10.0.0",
      "@nestjs/core": "^10.0.0"
    },
    "@liaoliaots/nestjs-redis-health": {
      "@nestjs/common": "^10.0.0",
      "@nestjs/core": "^10.0.0",
      "@nestjs/terminus": "^10.0.0"
    }
  },
```

**Comment by yhjs1211** [comment]
@mentos1386

Thanks a lot!!! It works :)

**Comment by liaoliaots** [comment]
Please check out the new version: version 10 of [@liaoliaots/nestjs-redis](https://www.npmjs.com/package/@liaoliaots/nestjs-redis/v/10.0.0).
